language: python
python:
  - "2.7"


sudo: required
services:
  - docker

compiler:
  - gcc
  - clang

before_install:


script:
  - ./scripts/build_containers
  - docker images | grep -q "codi\:test"
  - docker images | grep -q "toolchain\:test"
  - ./scripts/run_containers

notifications:
  email:
    recipients:
      - avery.brian@gmail.com
    on_success: change
    on_failure: always
