language: python
python:
  - "2.7"


sudo: required
compiler:
  - gcc
  - clang

before_install:


script: 
  ./test/buildcontainers

notifications:
  email:
    recipients:
      - avery.brian@gmail.com
    on_success: change
    on_failure: always
