language: python
python:
  - "2.7"


sudo: required
services:
  - docker

services:
    - docker

env:
    global:
        - DOCKER_VERSION=1.10.1-0~trusty


compiler:
  - gcc
  - clang

before_install:
  # list docker-engine versions
    - apt-cache madison docker-engine


script:
  - ./scripts/build_ceed
  - docker version
  - ./scripts/build_containers
  - docker images | grep codi | grep -q test
  - docker images | grep toolchain | grep -q test
  - docker images | grep zephyr | grep -q test
  - ./scripts/run_containers
  - python tests.py

notifications:
  email:
    recipients:
    on_success: change
    on_failure: always
