#!/usr/bin/env bash

# This is a sanity test script for the CODI and toolchain Docker images.
# This script has to be run from the dockerfiles directory.
#
# Example:
#
# ../tests/build_containers

TOPDIR=`git rev-parse --show-toplevel`
NUM_TOOLCHAINS=4

Q=`docker ps | egrep codi-test | awk '{print $1}'`
if [ "$Q"  != "" ]; then
    echo "Removing codi container"
    docker stop $Q;
    docker rm $Q
fi
Q=`docker images  -q crops/codi:test`
if [ "$Q"  != "" ]; then
    echo "Removing codi image"
    docker rmi -f $Q 
fi

Q=`docker images  -q crops/codi:deps`
if [ "$Q"  != "" ]; then
    echo "Removing codi deps image"
    docker rmi -f $Q 
fi

II=0
while [ $II -lt $NUM_TOOLCHAINS ]; do
    Q=`docker ps | egrep toolchain-test${II} | awk '{print $1}'`
    if [ "$Q"  != "" ]; then
	echo "Removing toolchain container $II"
	docker stop $Q;
	docker rm $Q
    fi
    let II=$II+1
done
Q=`docker images  -q crops/toolchain:test`
if [ "$Q"  != "" ]; then
    echo "Removing toolchain image"
    docker rmi -f   $Q
fi
Q=`docker images  -q crops/toolchain:deps`
if [ "$Q"  != "" ]; then
    echo "Removing toolchain deps image"
    docker rmi -f   $Q
fi




echo "Build CEED client"

make clean -C ${TOPDIR}/ceed/; make -C ${TOPDIR}/ceed/

cd ${TOPDIR}/dockerfiles;
echo "Build CODI deps image"
docker build -t crops/codi:deps -f Dockerfile.codi.deps ..

echo "Build CODI test image"
docker build -t crops/codi:test -f Dockerfile.codi ..

echo "Build toolchain deps image"
docker build -t crops/toolchain:deps -f Dockerfile.toolchain.deps ..

echo "Build toolchain test image"
docker build -t crops/toolchain:test -f Dockerfile.toolchain ..


echo "Start CODI container"
docker run -d --name codi-test -v /var/run/docker.sock:/var/run/docker.sock --net=host crops/codi:test


II=0
while [ $II -lt $NUM_TOOLCHAINS ]; do
    echo "Start toolchain container $II"
    docker run -d --name toolchain-test${II} -v /crops/:/crops/ --env TURFFID=crops/toolchain:test${II} --net=host crops/toolchain:test
    let II=$II+1
done

echo "List containers known to CODI"
sleep 3; ../ceed/ceed -l

echo "Stop and remove toolchain containers"
docker stop toolchain-test1; docker rm toolchain-test1
docker stop toolchain-test2; docker rm toolchain-test2
docker stop toolchain-test3; docker rm toolchain-test3
docker stop toolchain-test4; docker rm toolchain-test4

echo "Stop and remove CODI test container"
docker stop codi-test; docker rm codi-test

