#!/usr/bin/env bash

# This is a sanity test script for the CODI and toolchain Docker images.
# This removes the old test containers, and builds a new codi and 4 new test toolchains.  
# Then it runs ceed -l to talk to codi to list the 4 test toolchains
# If you do not have the deps containers, it will build them but this takes awhile
#
# Example:
#
# ./tests/build_containers

TOPDIR=`git rev-parse --show-toplevel`
NUM_TOOLCHAINS=4

Q=`docker ps | egrep codi-test | awk '{print $1}'`
if [ "$Q"  != "" ]; then
    echo "Removing codi container"
    docker stop $Q;
    docker rm $Q
fi
Q=`docker images  -q crops/codi:test`
if [ "$Q"  != "" ]; then
    echo "Removing codi image"
    docker rmi -f $Q  
fi


II=0
while [ $II -lt $NUM_TOOLCHAINS ]; do
    Q=`docker ps | egrep toolchain-test${II} | awk '{print $1}'`
    if [ "$Q"  != "" ]; then
	echo "Removing toolchain container $II"
	docker stop $Q;
	docker rm $Q
    fi
    let II=$II+1
done
Q=`docker images  -q crops/toolchain:test`
if [ "$Q"  != "" ]; then
    echo "Removing toolchain image"
    docker rmi -f   $Q
fi

echo "Build CEED client"

make clean -C ${TOPDIR}/ceed/; make -C ${TOPDIR}/ceed/

cd ${TOPDIR}/dockerfiles;

Q=`docker images  -q crops/codi:deps`
if [ "$Q"  == "" ]; then
    echo "Build CODI deps image"
    docker build -t crops/codi:deps -f Dockerfile.codi.deps --rm=true .. 
fi


echo "Build CODI test image"
docker build -t crops/codi:test -f Dockerfile.codi --rm=true .. 

Q=`docker images  -q crops/toolchain:deps`
if [ "$Q"  == "" ]; then
    echo "Build toolchain deps image"
    docker build -t crops/toolchain:deps -f Dockerfile.toolchain.deps  --rm=true .. 

fi

echo "Build toolchain test image"
docker build -t crops/toolchain:test -f Dockerfile.toolchain --rm=true ..


echo "Start CODI container"
docker run -d --name codi-test -v /var/run/docker.sock:/var/run/docker.sock --net=host crops/codi:test


II=0
while [ $II -lt $NUM_TOOLCHAINS ]; do
    echo "Start toolchain container $II"
    docker run -d --name toolchain-test${II} -v /crops/:/crops/ --env TURFFID=crops/toolchain:test${II} --net=host crops/toolchain:test
    let II=$II+1
done

echo "List containers known to CODI"
sleep 3; 
cd ${TOPDIR}/ceed
 if [ -e `which docker-machine` ]; then 
     ADDRESS=`docker-machine ip ${DOCKER_MACHINE_NAME}`
 else
     # linux can run over unix sockets rather than ip but ip is more cross platform
     ADDRESS=127.0.0.1
fi
./ceed -i $ADDRESS -s 10000 -l

echo "Stop and remove toolchain containers"
II=0
while [ $II -lt $NUM_TOOLCHAINS ]; do
    docker stop toolchain-test${II}; docker rm toolchain-test${II}
    let II=$II+1
done


echo "Stop and remove CODI test container"
docker stop codi-test; docker rm codi-test

